const TalentsMock = [
  {
    id: '1',
    nome: 'Alexandre Tobias da Silva',
    categoria: ['Front-end', 'Back-end'],
    competencias: ['HTML5', 'CSS3', 'React.js', 'Node.js'],
    labels: ['Liderança', 'Oratória'],
    experiencia: 'Pleno',
  },

  {
    id: '2',
    nome: 'Bruno Faria da Cunha',
    categoria: ['Back-end'],
    competencias: ['Node.js', 'SQL', 'MongoDB', 'Express'],
    labels: ['Oratória'],
    experiencia: 'Sênior',
  },
  {
    id: '3',
    nome: 'Gohan da Silva',
    categoria: ['Front-end'],
    competencias: ['Angular', 'Redux', 'UI'],
    labels: ['Liderança'],
    experiencia: 'Sênior',
  },
  {
    id: '4',
    nome: 'Joaquim da Silva',
    categoria: ['Front-end'],
    competencias: ['Angular', 'Redux', 'UI'],
    labels: ['Liderança'],
    experiencia: 'Sênior',
  },
  {
    id: '5',
    nome: 'Naruto Uzumaki',
    categoria: ['Front-end'],
    competencias: ['Angular', 'Redux', 'UI'],
    labels: ['Liderança'],
    experiencia: 'Sênior',
  },
  {
    id: '6',
    nome: 'Sasuke Uchiha',
    categoria: ['Front-end'],
    competencias: ['Angular', 'Redux', 'UI'],
    labels: ['Liderança'],
    experiencia: 'Sênior',
  },
  {
    id: '7',
    nome: 'João da Silva',
    categoria: ['Front-end'],
    competencias: ['Angular', 'Redux', 'UI'],
    labels: ['Liderança'],
    experiencia: 'Sênior',
  },
  {
    id: '8',
    nome: 'Palmirinha',
    categoria: ['Front-end'],
    competencias: ['Angular', 'Redux', 'UI'],
    labels: ['Liderança'],
    experiencia: 'Sênior',
  },
  {
    id: '9',
    nome: 'João Silveira',
    categoria: ['Front-end'],
    competencias: ['Angular', 'Redux', 'UI'],
    labels: ['Liderança'],
    experiencia: 'Sênior',
  },
  {
    id: '10',
    nome: 'Senhor robo',
    categoria: ['Front-end'],
    competencias: ['Angular', 'Redux', 'UI'],
    labels: ['Liderança'],
    experiencia: 'Sênior',
  },
];

export default TalentsMock;
