import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faCircle,
  faBars,
  faSearch,
  faChevronDown,
  faHome,
  faPaperPlane,
  faChartPie,
  faAddressBook,
  faMailBulk,
  faCommentAlt,
  faTimes,
  faBriefcase,
  faEllipsisV,
  faUserPlus,
  faPlusCircle,
  faIdBadge,
  faTimesCircle,
  faTrashAlt,
  faCheck,
  faChevronUp,
  faChevronRight,
  faChevronLeft,
  faColumns,
} from '@fortawesome/free-solid-svg-icons';

export default function() {
  library.add(
    faCircle,
    faBars,
    faChevronDown,
    faHome,
    faPaperPlane,
    faChartPie,
    faAddressBook,
    faMailBulk,
    faCheck,
    faCommentAlt,
    faTimes,
    faBriefcase,
    faEllipsisV,
    faUserPlus,
    faPlusCircle,
    faSearch,
    faIdBadge,
    faTimesCircle,
    faTrashAlt,
    faChevronUp,
    faChevronRight,
    faChevronLeft,
    faColumns,
  );
}
